### ISSUE TITLE
Will this work with http elk?

### ISSUE THREAD

**Issue by bossi6of9** [brunotm/elasticsplunk#12]
Hi,

I installed this app on a server, and pointed it to a local elk config, and it works as long as it just use "localhost:9200" for the elk server.  If i try to enter either http or https in the index address, it fails.  Any suggestions?

**Comment by ienliven** [comment]
you could put a nginx as http(s) proxy in front of ES

**Comment by brunotm** [comment]
@bossi6of9, does this issue still apply?

My current use is over https as in the README (eaddr="https://node1:9200,https://node2:9200") without problems.
